# Local: /root/recrutamentoia/docker-compose.yml (NO SEU SERVIDOR)

# --- Versão do Docker Compose ---
version: '3.8'

# --- Definição dos Serviços (Contêineres) ---
services:
  # --- Serviço do Backend (API) ---
  backend:
    image: orickjogando/recrutamentoia-backend:1.0.2
    # --- LINHA ADICIONADA AQUI ---
    # DOCUMENTAÇÃO: Esta linha instrui o Docker Compose a carregar todas as
    # variáveis de ambiente do arquivo especificado. Isso resolve o problema
    # do contêiner não encontrar as chaves do Google ao iniciar.
    env_file:
      - ./.env.production
    # -----------------------------
    networks:
      - traefik_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=Foco"
      # Roteador para a API
      - "traefik.http.routers.backend-router.rule=Host(`recrutamentoia.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-router.entrypoints=websecure"
      - "traefik.http.routers.backend-router.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.backend-router.priority=100"
      
  # --- Serviço do Frontend (React App) ---
  frontend:
    image: orickjogando/recrutamentoia-frontend:1.0.3
    networks:
      - traefik_network
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=Foco"
      # Roteador para o Frontend
      - "traefik.http.routers.frontend-router.rule=Host(`recrutamentoia.com.br`) || Host(`www.recrutamentoia.com.br`)"
      - "traefik.http.routers.frontend-router.entrypoints=websecure"
      - "traefik.http.routers.frontend-router.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.frontend-service.loadbalancer.server.port=80"

# --- Definição das Redes ---
networks:
  traefik_network:
    external: true
    name: Foco